const NpimDataDisplay = {

    id: 0,
    strCode: "",
    consumerBase: "",
    collection: "",
    itGroup: "",
    category: "",
    itemCode: "",
    catPB: "",
    stdWt: "",
    stdUCP: "",
    activity: "",
    complexity: "",
    si2Gh: "",
    vsGh: "",
    vvs1: "",
    i2Gh: "",
    si2Ij: "",
    shape: "",
    gender: "",
    videoLink: "",
    childNodesN: "",
    childNodesE: "",
    region: "",
    diamondWt: "",
    colourWt: "",
    metalWt: "",
    findings: "",
    metalColor: "",
    parentItemCode: "",
    itemLevelType: "",
    npimEventNo: "",
    rsoName: "",
    doe: "",
    saleable: "",
    size: "",
    uom: "",
    reasons: "",
    indQty: "",
    indCategory: "",
    submitStatus: "",
    set2Type: "",
    stoneQuality: "",
    stoneQualityVal: "",
    scannedCount: "",
    unscannedCount: "",
    indentLevelType: ""
};

const IndentProductInsertL3 = {

    itemCode: "",
    strCode: "",
    saleable: "",
    childNodesE: "",
    childNodesN: "",
    reasons: "",
    findings: "",
    indQty: "",
    indCategory: "",
    submitStatus: "",
    set2Type: "",
    stoneQuality: "",
    stoneQualityVal: "",
    rSOName: "",
    npimEventNo: "",
    indentLevelType: "",
    collection: "",
    consumerbase: "",
    itgroup: "",
    category: "",
    sizeUomQuantitys: [],
    sizeQuantitys: [],
    tagQuantitys: [],
};
export { IndentProductInsertL3 };
export default NpimDataDisplay;